version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
      - "8000-8005:8000-8005"
    environment:
      - PORT=8080
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=azuracast
      # Las credenciales de la base de datos se configurarán en Railway
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=azuracast
      # Las credenciales de la base de datos se configurarán en Railway
    restart: unless-stopped
