version: '3.8'

services:
  web:
    build: .
    ports:
      - "${PORT:-3000}:3000"
      - "8000-8005:8000-8005"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=azuracast
      - MYSQL_PASSWORD=azuracast_pw
      - MYSQL_DATABASE=azuracast
      - PREFER_RELEASE_BUILDS=true
      - COMPOSER_PLUGIN_MODE=false
      - ENABLE_REDIS=false
      - ENABLE_WEB_UPDATER=false
      - PORT=3000
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=azuracast
      - MYSQL_USER=azuracast
      - MYSQL_PASSWORD=azuracast_pw
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 5s
    restart: unless-stopped

volumes:
  db_data:
